# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
docker-registry:
  enabled: false

chartmuseum:
  image:
    repository: chartmuseum/chartmuseum
    tag: v0.7.1
  persistence:
    storageClass: "nfs-client"
    size: 20Gi

jenkins:
  Master:
    Image: jenkinsxio/jenkinsx
    ImageTag: 0.0.70
    ServiceType: ClusterIP
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: "harbor.njbandou.com"
  Agent:
    PodTemplates:
      Maven:
        Containers:
          Maven:
            Image: harbor.njbandou.com/library/builder-jx:0.1.595
  Persistence:
    storageClass: "nfs-client"
    Size: 20Gi

nexus:
  enabled: true
  image:
    repository: docker pull harbor.njbandou.com/library/nexus
    tag: 0.1.7
  persistence:
    storageClass: "nfs-client"
    size: 20Gi

monocular:
  enabled: false
  heapster:
    image:
      repository: docker pull harbor.njbandou.com/library/heapster
      tag: v1.5.2
    resizer:
      image:
        repository: docker pull harbor.njbandou.com/library/addon-resizer
        tag: 1.7
